# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Language Metrics

on:
  # Schedule updates (each day)
  schedule: [{cron: "* 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  language-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          base: ""
          filename: metrics-languages.svg
          config_timezone: Europe/Paris
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
