# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Achievement Metrics

on:
  # Schedule updates (each day)
  schedule: [{cron: "* 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  achievement-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@96dde98a034ab75fec7884f9161bc12759275d36  # todo: temp fix, go back to latest once merged
      # - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: fsoubelet
          template: classic
          base: ""
          filename: metrics-achievements.svg
          config_timezone: Europe/Paris
          plugin_achievements: yes
          plugin_achievements_limit: 6
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
#          plugin_achievements_display: compact
          repositories: 200
